- name: Install gh
  ansible.builtin.package:
    name: gh
    state: present

- name: Install github
  community.general.homebrew_cask:
    name: github
    state: present
  when: ansible_distribution == 'MacOSX'
