- name: Create screenshots directory
  ansible.builtin.file:
    path: ~/Screenshots
    state: directory
    mode: '0755'
  when: ansible_distribution == 'MacOSX'

- name: Set screenshots directory
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: location
    type: string
    value: "~/Screenshots"
    state: present
  when: ansible_distribution == 'MacOSX'
  notify: restart_system_ui_server

- name: Set screenshots to PNG format
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: type
    type: string
    value: "png"
    state: present
  when: ansible_distribution == 'MacOSX'
  notify: restart_system_ui_server

- name: Disable screenshot shadow
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: disable-shadow
    type: bool
    value: true
    state: present
  when: ansible_distribution == 'MacOSX'
  notify: restart_system_ui_server

- name: Set floating thumbnail timeout
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: autohide-delay
    type: float
    value: 1
    state: present
  when: ansible_distribution == 'MacOSX'
  notify: restart_system_ui_server

- name: Disable screenshot sound
  community.general.osx_defaults:
    domain: com.apple.systemsound
    key: com.apple.sound.uiaudio.enabled
    type: int
    value: 0
    state: present
  when: ansible_distribution == 'MacOSX'
  notify: restart_system_ui_server
