#!/usr/bin/expect -f
set key_file [lindex $argv 0]
set hostname [lindex $argv 1]
set password [lindex $argv 2]

spawn ssh-copy-id -i $key_file $hostname
expect "assword:"
send "$password\r";
expect eof