---
- name: Bootstrap
  hosts: 127.0.0.1
  connection: local

  tasks:
  - name: Install git
    ansible.builtin.package:
      name: git
      state: present

  - name: Install mas
    ansible.builtin.package:
      name: mas
      state: present

  - name: Install wget
    ansible.builtin.package:
      name: wget
      state: present

  - name: Install ansible
    ansible.builtin.package:
      name: ansible
      state: present

  - name: Install 1password
    community.general.homebrew_cask:
      name: 1password
      state: present

  - name: Install zoom
    community.general.homebrew_cask:
      name: zoom
      state: present
