#!/usr/bin/env bash

# Exit if command fails
set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
DOTFILES_DIR=$SCRIPT_DIR/../.dotfiles

cleanup() {
    exit_code=$?
    if [[ ${exit_code} -eq 0 ]]; then
        if [[ `which terminal-notifier` != "" ]]; then
            terminal-notifier -title "Dotfiles: setup complete" -message "Successfully set up environment." -appIcon "file://$SCRIPT_DIR/../.dotfiles/assets/robot_emoji.png"
        fi
        echo $(green "Successfully set up environment.")
    else
        if [[ `which terminal-notifier` != "" ]]; then
            terminal-notifier -title "Dotfiles: error" -message "Error setting up environment." -appIcon "file://$SCRIPT_DIR/../.dotfiles/assets/robot_emoji.png"
        fi

        echo $(red "Error setting up environment")
    fi
}

trap cleanup EXIT

function red {
    RED='\033[0;31m'
    RESET_COLOR='\033[0m'
    printf "${RED}$@${RESET_COLOR}\n"
}

function green {
    GREEN='\033[0;32m'
    RESET_COLOR='\033[0m'
    printf "${GREEN}$@${RESET_COLOR}\n"
}

function yellow {
    YELLOW='\033[0;33m'
    RESET_COLOR='\033[0m'
    printf "${YELLOW}$@${RESET_COLOR}\n"
}

echo $(green "Confirming python3...")
if [[ `which python3` = "" ]]; then
    echo $(red "python3 is not in the path!")
    exit 1
fi

if [[ `which ansible-playbook` = "" ]]; then
    echo $(green "Downloading ansible and running playbook...")
    python3 $DOTFILES_DIR/assets/pipx.pyz run --spec ansible ansible-playbook --connection=local -i $DOTFILES_DIR/playbook/hosts $DOTFILES_DIR/playbook/main.yml
else
    echo $(yellow "Skipped ansible installation")
    echo $(green "Running ansible playbook...")
    ansible-playbook --connection=local -i $DOTFILES_DIR/playbook/hosts $DOTFILES_DIR/playbook/main.yml
fi
