- name: Install pipx
  ansible.builtin.package:
    name: pipx
    state: present

- name: Add pipx completions
  ansible.builtin.command: pipx completions

# - name: Ensure pipx path
#   ansible.builtin.command: pipx ensurepath
